#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/installers/shared.sh"

require_installer package-manager
require_installer os
require_installer git
require_installer devtools
require_installer devdeps
require_installer fonts
require_installer zsh
require_installer tmux
require_installer neovim
require_installer haskell
require_installer ruby
