#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

dotheader "Setting up devtools..."

install_package libpq # postgres tools like psql and pg_dump
install_package ripgrep
install_package wget

# Hold osx's hand
brew_install fd
brew_install coreutils
brew_install gnu-tar
brew_install hub
