#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

function setup_user_gitconfig() {
  config_name=$1

  if [ ! -f ~/.gitconfig.user.${config_name} ]; then
    printf "What is your ${config_name} GitHub username? > "
    read github_user
    git config -f ~/.gitconfig.user.$config_name github.user "$github_user"

    printf "What is your full name for ${config_name} commit messages (e.g. Jane Smith)? > "
    read git_name
    git config -f ~/.gitconfig.user.${config_name} user.name "$git_name"

    printf "What is your ${config_name} git email? (e.g. blah@blah.com) > "
    read git_email
    git config -f ~/.gitconfig.user.${config_name} user.email "$git_email"
  fi
}

function setup_git_dotfiles() {
  symlink_dotfile git/gitconfig ~/.gitconfig
  symlink_dotfile git/gitignore ~/.gitignore
  symlink_dotfile git/gitmessage ~/.gitmessage
}

function install_git() {
  if is_google_macos; then
    echo "On Google MacOS, skipping git install..."
  else
    dotheader "Setting up Git..."
    install_package "git"
  fi
}


brew_install diff-so-fancy

install_git

setup_user_gitconfig "personal"
setup_user_gitconfig "work"
setup_git_dotfiles
