#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

function setup_rvmrc() {
  symlink_dotfile rvmrc ~/.rvmrc
}

function install_latest_ruby() {
  rvm install ruby --latest
}

function install_global_gem_hooks() {
  local dest="$HOME/.rvm/hooks/after_install_add_default_gems"

  symlink_dotfile rvm/hooks/after_install_add_default_gems $dest
  chmod +x $dest
}

function install_rvm() {
  if [ ! -e ~/.rvm ]; then
    \curl -L https://get.rvm.io | bash -s -- --ignore-dotfiles

    export PATH="$HOME/.rvm/bin:$PATH"
    [ -f ~/.rvm/scripts/rvm ] && source ~/.rvm/scripts/rvm

    install_global_gem_hooks
    install_latest_ruby
  fi
}

function setup_pry() {
  symlink_dotfile irb/pryrc ~/.pryrc
  symlink_dotfile irb/unescaped_colors.rb ~/.unescaped_colors.rb
  symlink_dotfile irb/escaped_colors.rb ~/.escaped_colors.rb
  symlink_dotfile irb/aprc ~/.aprc
}

function bootstrap_rvm() {
  dotsay "@b@blue[[Installing RVM...]]"
  setup_rvmrc
  install_rvm
  install_global_gem_hooks
}

dotheader "Setting up Ruby..."

symlink_dotfile gemrc ~/.gemrc

setup_pry
bootstrap_rvm
