#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

function setup_zsh_symlinks() {
  symlink_dotfile zshrc ~/.zshrc
  symlink_dotfile zsh ~/.zsh
}

function zsh_binary() {
  if is_linux; then
    echo /bin/zsh
  elif is_macos; then
    if is_google_macos; then
      echo /bin/zsh
    else
      echo /usr/local/bin/zsh
    fi
  fi
}

function update_shell_whitelist() {
  local zshbin=$(zsh_binary)
  if ! cat /etc/shells | grep -q $zshbin; then
    echo "Adding $zshbin to /etc/shells, please enter your sudo password"

    echo $zshbin | sudo tee -a /etc/shells > /dev/null
  fi
}

function chsh_zsh() {
  if [[ "$SHELL" != "$(zsh_binary)" ]]; then
    local current_user=$USER
    dotsay "@b@blue[[Changing shell for $current_user...]]"

    if is_google_linux; then
      local corp_user="$current_user.corp"
      prodaccess 2>&1 >/dev/null
      local ganpati_output=$(ganpati2 user edit --id=$corp_user --corp_shell=$(zsh_binary) --approve_now=true 2>&1)

      if [[ "$ganpati_output" =~ "Proposal proposes current state" ]]; then
        dotsay "@b@blue[[Shell already set, no changes made.]]"
      else
        dotsay "@b@red[[Changed corp shell entry for $corp_user, machine reboot is required!]]"
      fi
    else
      sudo chsh -s $(zsh_binary) $current_user
    fi
  fi
}

function install_fzf() {
  if [ ! -d ~/.fzf ]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  fi

  if [ ! -f $HOME/.fzf.zsh ]; then
    ~/.fzf/install
  fi
}

function install_fasd() {
  if is_linux; then
    if ! command_exists "fasd"; then
      sudo add-apt-repository ppa:aacebedo/fasd
      sudo apt-get update
    fi
  fi

  install_package fasd
}

function install_antigen() {
  local plugin_file=$HOME/.zsh/vendor/antigen.zsh

  if [ ! -f $plugin_file ]; then
    echo "Installing antigen"
    curl -L git.io/antigen > "$plugin_file"
  fi
}

function install_base16_shell() {
  local base16_repo=$HOME/.config/base16-shell

  if [ ! -d $base16_repo ]; then
    echo "Installing base16-shell..."
    git clone https://github.com/chriskempson/base16-shell.git "$base16_repo"
  fi
}

dotheader "Setting up ZSH..."

brew_install neofetch
install_base16_shell
install_package zsh
install_fasd

#install_fzf

setup_zsh_symlinks
install_antigen

update_shell_whitelist
chsh_zsh
